version: "3.9"

services:

  # database
  mongodb:
    image: mongo:latest
    container_name: pfa-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: meiezbr
      MONGO_INITDB_ROOT_PASSWORD: 159357
    networks:
      - pfa-net
    # labels:
    #  - com.prometheus.scrape=true
    #  - com.prometheus.port=9100

  # mongodb exporter
  # mongodb-exporter:
  #   image: bitnami/node-exporter:latest
  #   container_name: pfa-mongodb-exporter
  #   environment:
  #     MONGODB_HOST: mongodb
  #     MONGODB_DATABASE: admin
  #     MONGODB_USER: meiezbr
  #     MONGODB_PASSWORD: 159357
  #   ports:
  #     - 9100:9100
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #   depends_on:
  #     - mongodb
  #   hostname: mongodb

  # prometheus
  # prometheus:
  #   image: "prom/prometheus"
  #   container_name: pfa-prometheus
  #   ports:
  #     - "9090:9090"  
  #   volumes:
  #     - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #   depends_on:
  #     - backend
  #     - mongodb
  #   networks:
  #     - pfa-net

  # grafana
  # grafana:
  #   image: grafana/grafana
  #   container_name: pfa-grafana
  #   ports:
  #     - "3001:3000"  
  #   volumes:
  #     - ./grafana:/var/lib/grafana  
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=password
  #     - PORT=8000
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - pfa-net
  
  # backend
  backend:
    container_name: pfa-backend
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_DATABASE: admin
      MONGODB_USER: meiezbr
      MONGODB_PASSWORD: 159357
    depends_on:
      - mongodb
    networks:
      - pfa-net
    # hostname: backend
    # labels:
    #  - com.prometheus.scrape=true
    #  - com.prometheus.port=5000
  
  # frontend
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: pfa-frontend
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mongodb
      - backend
    networks:
      - pfa-net
    volumes:
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # hostname: frontend

# volumes
volumes:
  mongodb_data:

# networks
networks:
  pfa-net:
    name: pfa-net
    driver: bridge