version: "3.9"

services:

  # nexus arm
  nexuscon:
    image: sonatype/nexus3:latest
    container_name: nexuscon
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - pfa-net

  # # database
  # mongodb:
  #   image: mongo:latest
  #   container_name: pfa-db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: meiezbr
  #     MONGO_INITDB_ROOT_PASSWORD: 159357
  #   networks:
  #     - pfa-net
  #   labels:
  #    - com.prometheus.scrape=true
  #    - com.prometheus.port=9100

  # # mongodb exporter
  # mongodb-exporter:
  #   image: bitnami/node-exporter:latest
  #   container_name: pfa-mongodb-exporter
  #   environment:
  #     MONGODB_HOST: mongodb
  #     MONGODB_DATABASE: admin
  #     MONGODB_USER: meiezbr
  #     MONGODB_PASSWORD: 159357
  #   ports:
  #     - 9100:9100
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #   depends_on:
  #     - mongodb
  #   hostname: mongodb

  # # prometheus
  # prometheus:
  #   image: "prom/prometheus"
  #   container_name: pfa-prometheus
  #   ports:
  #     - "9090:9090"  
  #   volumes:
  #     - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #   depends_on:
  #     - backend
  #     - mongodb
  #   networks:
  #     - pfa-net

  # # grafana
  # grafana:
  #   image: grafana/grafana
  #   container_name: pfa-grafana
  #   ports:
  #     - "3001:3000"  
  #   volumes:
  #     - ./grafana:/var/lib/grafana  
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=password
  #     - PORT=8000
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - pfa-net
  
  # backend
  backend:
    container_name: pfa-backend
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "5000:5000"
    environment:
      # cloud database
      MONGODB_HOST_FILE: /run/secrets/mongodb_host
      MONGODB_DATABASE_FILE: /run/secrets/mongodb_database
      MONGODB_USER_FILE: /run/secrets/mongodb_user
      MONGODB_PASSWORD_FILE: /run/secrets/mongodb_password
    depends_on:
      # - mongodb
      - nexuscon
    networks:
      - pfa-net
    hostname: backend
    labels:
     - com.prometheus.scrape=true
     - com.prometheus.port=5000
    secrets:
      - mongodb_host
      - mongodb_database
      - mongodb_user
      - mongodb_password
  
  # frontend
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: pfa-frontend
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      # - mongodb
      - nexuscon
      - backend
    networks:
      - pfa-net
    volumes:
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/nginx/cors.conf:/etc/nginx/cors.conf:ro
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    hostname: frontend

secrets:
  mongodb_host:
    file: ./secrets/mongodb_host.txt
  mongodb_database:
    file: ./secrets/mongodb_database.txt
  mongodb_user:
    file: ./secrets/mongodb_user.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt

# volumes
volumes:
#   mongodb_data:
  nexus-data:
    external: true

# networks
networks:
  pfa-net:
    name: pfa-net
    driver: bridge